# Dependabot version updates
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups: # group all Oxlint updates together
      oxlint:
        patterns:
          - 'oxlint'
    commit-message: # keep the history tidy
      prefix: 'chore'
      include: 'scope'
    ignore: # optional: ignore future majors
      - dependency-name: 'oxlint'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
