name: Validate PR

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Set up pnpm
        uses: pnpm/action-setup@v4.3.0

      - name: Get node version
        id: get-node-version
        run: |
          NODE_VERSION=$(cat .nvmrc)
          echo "NODE_VERSION=${NODE_VERSION}"
          echo "node-version=${NODE_VERSION}" >> $GITHUB_OUTPUT

      - name: Set up node ${{ steps.get-node-version.outputs.node-version }}
        uses: actions/setup-node@v6.3.0
        with:
          node-version: ${{ steps.get-node-version.outputs.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Knip
        run: pnpm knip

      - name: TypeScript check
        run: pnpm ts-check

      - name: Lint & format
        run: pnpm check

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build

      - name: Manage labels
        id: manage-labels
        uses: ./.github/actions/manage-github-labels
        with:
          labels-to-add: "pr-in-progress, testing"
          labels-to-remove: "merged"
          github-token: ${{ github.token }}

      - name: Add message to summary
        run: echo "${{ steps.manage-labels.outputs.markdown-message }}" >> $GITHUB_STEP_SUMMARY
